### ISSUE TITLE
npm run make error

### ISSUE THREAD

**Issue by aral** [felixrieseberg/windows95#19]
On Pop!_OS 18.04 (based on Ubuntu 18.04):

```
✖ Making for target: rpm - On platform: linux - For arch: x64

An unhandled error has occurred inside Forge:
An error occured while making for target: rpm
Error executing command (spawn rpmbuild ENOENT): 
rpmbuild -bb /tmp/electron-118723-1021-6kvhff.t153q/windows95_1.0.0_x86_64/SPECS/windows95.spec --target x86_64

Error: Error executing command (spawn rpmbuild ENOENT): 
rpmbuild -bb /tmp/electron-118723-1021-6kvhff.t153q/windows95_1.0.0_x86_64/SPECS/windows95.spec --target x86_64

    at ChildProcess.<anonymous> (/home/aral/sandbox/windows95/node_modules/electron-installer-redhat/src/installer.js:55:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! windows95@1.0.0 make: `electron-forge make`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the windows95@1.0.0 make script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aral/.npm/_logs/2018-08-23T22_21_53_600Z-debug.log
```

`npm run start` does work but app fails with no bootable image found.

What’s the expected way to run this? (And thanks for the late-night chuckles) :)

**Comment by felixrieseberg** [comment]
It seems you don't have `rpmbuild` installed - but the actual issue is that you don't have the `images` since they're not part of the git repo. Let me update the readme with a bit of info!

**Comment by aral** [comment]
Ah, I wasn’t sure if they were downloaded during the build or not (I saw the node_modules folder was ~400MB or so.) Thanks! :)

**Comment by dofamin-1** [comment]
sorry, but what was the solution?
