### ISSUE TITLE
npm run make / "electron-forge make"

### ISSUE THREAD

**Issue by dofamin-1** [felixrieseberg/windows95#206]
Based on Ubuntu 20.04:

```
> event-electron@1.0.0 make /home/sargsyan/Downloads/test/event-electron
> electron-forge make

✔ Checking your system
✔ Resolving Forge Config
We need to package your application before we can make it
✔ Preparing to Package Application for arch: x64
✔ Compiling Application
✔ Preparing native dependencies
✔ Packaging Application
Making for the following targets:
✔ Making for target: deb - On platform: linux - For arch: x64
✖ Making for target: rpm - On platform: linux - For arch: x64

An unhandled error has occurred inside Forge:
An error occured while making for target: rpm
Error executing command (spawn rpmbuild ENOENT): 
rpmbuild -bb /tmp/electron-2021022-159468-1wt7kt1.xwzl/event-electron_1.0.0_x86_64/SPECS/event-electron.spec --target x86_64

Error: Error executing command (spawn rpmbuild ENOENT): 
rpmbuild -bb /tmp/electron-2021022-159468-1wt7kt1.xwzl/event-electron_1.0.0_x86_64/SPECS/event-electron.spec --target x86_64

    at ChildProcess.<anonymous> (/home/sargsyan/Downloads/test/event-electron/node_modules/electron-installer-redhat/src/installer.js:55:23)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:607:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! event-electron@1.0.0 make: `electron-forge make`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the event-electron@1.0.0 make script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-21T21_38_10_909Z-debug.log
```

`npm run start` does work (as well as `npm run package` / creates `out` folder in for electron app). But  gets the above output   while running `npm run make`
thank you in advance... :)

**Comment by felixrieseberg** [comment]
`spawn rpmbuild ENOENT` just means the `rpm` tooling isn't installed on your build machine — `sudo apt install rpm` and `electron-forge make` will get past it (or make only the deb target). Closing.
